Generated: true
General:
  Language: en_US
DClock:
  Position:
    X: 40
    Y: 120
  Clock:
    Font:
      Size: 76
      Name: Exo Thin
      Layout: Left
      Color:
        Red: 255
        Green: 255
        Blue: 255
    Time:
      UseTwentyFourHours: true
  DDate:
    Position:
      Offset:
        X: 0
        Y: 80
    Show: true
    Font:
      Size: 40
      Name: Exo Thin
      Layout: Left
      Color:
        Red: 255
        Green: 255
        Blue: 255
DCalendar:
  Position:
    Offset:
      X: 0
      Y: 180
  Font:
    Name: Exo Light
    Size: 18
  Headers:
    Font:
      Color:
        Red: 255
        Green: 255
        Blue: 255
  Dates:
    InMonth:
      Font:
        Color:
          Red: 255
          Green: 255
          Blue: 255
    NotInMonth:
      Font:
        Color:
          Red: 255
          Green: 255
          Blue: 255
