Generated: true
General:
  Language: en_US
DClock:
  Position:
    X: 40
    Y: 120
  Clock:
    Font:
      Size: 76
      Name: Exo Thin
      Layout: Left
      Color:
        Red: 255
        Green: 255
        Blue: 255
    Time:
      UseTwentyFourHours: true
  DDate:
    Show: true
    Font:
      Size: 40
      Name: Exo Thin
      Layout: Left
      Color:
        Red: 255
        Green: 255
        Blue: 255
    Position:
      Offset:
        X: 0
        Y: 80
DCalendar:
  Font:
    Size: 30
    Name: Exo Thin
    Layout: Left
    Color:
      Red: 255
      Green: 255
      Blue: 255
  Position:
    Offset:
      X: 0
      Y: 120
